---
title: "The Other 14"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(tidyverse)

source("draft-script.R")

PL_raw_data <- read_csv("data/sportsref_download_PL_210419.csv")
LaLiga_raw_data <- read_csv("data/sportsref_download_LaLiga_210419.csv")
SerieA_raw_data <- read_csv("data/sportsref_download_SerieA_210419.csv")
```

Column {.tabset}
-----------------------------------------------------------------------

### English Premier League

```{r}
PL_raw_data %>%
  Tidy_Data() %>%
  Updated_League_Table() %>%
  filter(Points_Gain >= 0) %>%
  DT::datatable(rownames = T,
                options = list(scroller = TRUE)
  )
```

### Italian Serie A

```{r}
SerieA_raw_data %>%
  Tidy_Data() %>%
  Updated_League_Table() %>%
  filter(Points_Gain >= 0) %>%
  DT::datatable(rownames = T,
                options = list(scroller = TRUE)
  )
```

### Spanish La Liga

```{r}
LaLiga_raw_data %>%
  Tidy_Data() %>%
  Updated_League_Table() %>%
  filter(Points_Gain >= 0) %>%
  DT::datatable(rownames = T,
                options = list(scroller = TRUE)
  )
```

Column
-----------------------------------------------------------------------

### Chart B

```{r}

```

